baseurl = "https://beamalsky.fyi/"
title = "beamalsky.fyi"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-113596479-1"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "pink"
  description = "beamalsky.fyi"
  copyright = ""
  sidebarAbout = [
    "Civic journalism, new media, procedural rhetoric",
    "ğŸ“ the South Side of Chicago",
    "<b>Currently</b><br>ğŸŒº &nbsp; Events + books at Build Coffee<br>ğŸŒº &nbsp; Games + reproductive justice at Game Changer Chicago",
    "<b>Alum</b><br>ğŸŒ» &nbsp; South Side Weekly<br>ğŸŒ» &nbsp; UChicago"
  ]
  email = "beamalsky@gmail.com"

  # Nav links in the side bar
  # [[params.navlinks]]
  # name = "Home"
  # url = ""

  # [[params.navlinks]]
  # name = "About"
  # url = "about/"

  # [[params.navlinks]]
  # name = "Get in touch"
  # url = "contact/"

[params.social]
  # facebook      = "full page or profile url in facebook"
  # googleplus    = "full profile url in googleplus"
  email           = "beamalsky@gmail.com"
  twitter         = "https://twitter.com/beamalsky"
  # linkedin      = "full profile url in linkedin"
  # stackoverflow = "full profile url in stackoverflow"
  instagram       = "https://www.instagram.com/beamalsky/"
  github          = "https://github.com/beamalsky"
